// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: borrowers.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const archiveBorrower = `-- name: ArchiveBorrower :exec
UPDATE warehouse.borrowers
SET is_archived = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveBorrower(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveBorrower, id)
	return err
}

const createBorrower = `-- name: CreateBorrower :one
INSERT INTO warehouse.borrowers (id, workspace_id, name, email, phone, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, name, email, phone, notes, is_archived, created_at, updated_at, search_vector
`

type CreateBorrowerParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Email       *string   `json:"email"`
	Phone       *string   `json:"phone"`
	Notes       *string   `json:"notes"`
}

func (q *Queries) CreateBorrower(ctx context.Context, arg CreateBorrowerParams) (WarehouseBorrower, error) {
	row := q.db.QueryRow(ctx, createBorrower,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
	)
	var i WarehouseBorrower
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getBorrower = `-- name: GetBorrower :one
SELECT id, workspace_id, name, email, phone, notes, is_archived, created_at, updated_at, search_vector FROM warehouse.borrowers
WHERE id = $1 AND workspace_id = $2
`

type GetBorrowerParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetBorrower(ctx context.Context, arg GetBorrowerParams) (WarehouseBorrower, error) {
	row := q.db.QueryRow(ctx, getBorrower, arg.ID, arg.WorkspaceID)
	var i WarehouseBorrower
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const hasActiveLoans = `-- name: HasActiveLoans :one
SELECT EXISTS(
    SELECT 1 FROM warehouse.loans
    WHERE borrower_id = $1 AND returned_at IS NULL
)
`

func (q *Queries) HasActiveLoans(ctx context.Context, borrowerID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveLoans, borrowerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBorrowers = `-- name: ListBorrowers :many
SELECT id, workspace_id, name, email, phone, notes, is_archived, created_at, updated_at, search_vector FROM warehouse.borrowers
WHERE workspace_id = $1 AND is_archived = false
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListBorrowersParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListBorrowers(ctx context.Context, arg ListBorrowersParams) ([]WarehouseBorrower, error) {
	rows, err := q.db.Query(ctx, listBorrowers, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseBorrower{}
	for rows.Next() {
		var i WarehouseBorrower
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Notes,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreBorrower = `-- name: RestoreBorrower :exec
UPDATE warehouse.borrowers
SET is_archived = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreBorrower(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreBorrower, id)
	return err
}

const searchBorrowers = `-- name: SearchBorrowers :many
SELECT id, workspace_id, name, email, phone, notes, is_archived, created_at, updated_at, search_vector FROM warehouse.borrowers
WHERE workspace_id = $1
  AND is_archived = false
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT $3
`

type SearchBorrowersParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) SearchBorrowers(ctx context.Context, arg SearchBorrowersParams) ([]WarehouseBorrower, error) {
	rows, err := q.db.Query(ctx, searchBorrowers, arg.WorkspaceID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseBorrower{}
	for rows.Next() {
		var i WarehouseBorrower
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Notes,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBorrower = `-- name: UpdateBorrower :one
UPDATE warehouse.borrowers
SET name = $2, email = $3, phone = $4, notes = $5, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, email, phone, notes, is_archived, created_at, updated_at, search_vector
`

type UpdateBorrowerParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email *string   `json:"email"`
	Phone *string   `json:"phone"`
	Notes *string   `json:"notes"`
}

func (q *Queries) UpdateBorrower(ctx context.Context, arg UpdateBorrowerParams) (WarehouseBorrower, error) {
	row := q.db.QueryRow(ctx, updateBorrower,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
	)
	var i WarehouseBorrower
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
