// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCategory = `-- name: ArchiveCategory :exec
UPDATE warehouse.categories
SET is_archived = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveCategory, id)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO warehouse.categories (id, workspace_id, name, parent_category_id, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, parent_category_id, description, is_archived, created_at, updated_at
`

type CreateCategoryParams struct {
	ID               uuid.UUID   `json:"id"`
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
	Name             string      `json:"name"`
	ParentCategoryID pgtype.UUID `json:"parent_category_id"`
	Description      *string     `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (WarehouseCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ParentCategoryID,
		arg.Description,
	)
	var i WarehouseCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM warehouse.categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, workspace_id, name, parent_category_id, description, is_archived, created_at, updated_at FROM warehouse.categories
WHERE id = $1 AND workspace_id = $2
`

type GetCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (WarehouseCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.WorkspaceID)
	var i WarehouseCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasChildren = `-- name: HasChildren :one
SELECT EXISTS(
    SELECT 1 FROM warehouse.categories
    WHERE parent_category_id = $1 AND is_archived = false
)
`

func (q *Queries) HasChildren(ctx context.Context, parentCategoryID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasChildren, parentCategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, workspace_id, name, parent_category_id, description, is_archived, created_at, updated_at FROM warehouse.categories
WHERE workspace_id = $1 AND is_archived = false
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, workspaceID uuid.UUID) ([]WarehouseCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseCategory{}
	for rows.Next() {
		var i WarehouseCategory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentCategoryID,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByParent = `-- name: ListCategoriesByParent :many
SELECT id, workspace_id, name, parent_category_id, description, is_archived, created_at, updated_at FROM warehouse.categories
WHERE workspace_id = $1 AND parent_category_id = $2 AND is_archived = false
ORDER BY name
`

type ListCategoriesByParentParams struct {
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
	ParentCategoryID pgtype.UUID `json:"parent_category_id"`
}

func (q *Queries) ListCategoriesByParent(ctx context.Context, arg ListCategoriesByParentParams) ([]WarehouseCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByParent, arg.WorkspaceID, arg.ParentCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseCategory{}
	for rows.Next() {
		var i WarehouseCategory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentCategoryID,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT id, workspace_id, name, parent_category_id, description, is_archived, created_at, updated_at FROM warehouse.categories
WHERE workspace_id = $1 AND parent_category_id IS NULL AND is_archived = false
ORDER BY name
`

func (q *Queries) ListRootCategories(ctx context.Context, workspaceID uuid.UUID) ([]WarehouseCategory, error) {
	rows, err := q.db.Query(ctx, listRootCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseCategory{}
	for rows.Next() {
		var i WarehouseCategory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentCategoryID,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCategory = `-- name: RestoreCategory :exec
UPDATE warehouse.categories
SET is_archived = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreCategory, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE warehouse.categories
SET name = $2, parent_category_id = $3, description = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, parent_category_id, description, is_archived, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	ParentCategoryID pgtype.UUID `json:"parent_category_id"`
	Description      *string     `json:"description"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (WarehouseCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentCategoryID,
		arg.Description,
	)
	var i WarehouseCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
