// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: containers.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const archiveContainer = `-- name: ArchiveContainer :exec
UPDATE warehouse.containers
SET is_archived = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveContainer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveContainer, id)
	return err
}

const containerShortCodeExists = `-- name: ContainerShortCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM warehouse.containers
    WHERE workspace_id = $1 AND short_code = $2
)
`

type ContainerShortCodeExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ShortCode   *string   `json:"short_code"`
}

func (q *Queries) ContainerShortCodeExists(ctx context.Context, arg ContainerShortCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, containerShortCodeExists, arg.WorkspaceID, arg.ShortCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createContainer = `-- name: CreateContainer :one
INSERT INTO warehouse.containers (id, workspace_id, name, location_id, description, capacity, short_code)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at
`

type CreateContainerParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	LocationID  uuid.UUID `json:"location_id"`
	Description *string   `json:"description"`
	Capacity    *string   `json:"capacity"`
	ShortCode   *string   `json:"short_code"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (WarehouseContainer, error) {
	row := q.db.QueryRow(ctx, createContainer,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.LocationID,
		arg.Description,
		arg.Capacity,
		arg.ShortCode,
	)
	var i WarehouseContainer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.LocationID,
		&i.Description,
		&i.Capacity,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM warehouse.containers WHERE id = $1
`

func (q *Queries) DeleteContainer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContainer, id)
	return err
}

const getContainer = `-- name: GetContainer :one
SELECT id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.containers
WHERE id = $1 AND workspace_id = $2
`

type GetContainerParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetContainer(ctx context.Context, arg GetContainerParams) (WarehouseContainer, error) {
	row := q.db.QueryRow(ctx, getContainer, arg.ID, arg.WorkspaceID)
	var i WarehouseContainer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.LocationID,
		&i.Description,
		&i.Capacity,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContainerByShortCode = `-- name: GetContainerByShortCode :one
SELECT id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.containers
WHERE workspace_id = $1 AND short_code = $2
`

type GetContainerByShortCodeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ShortCode   *string   `json:"short_code"`
}

func (q *Queries) GetContainerByShortCode(ctx context.Context, arg GetContainerByShortCodeParams) (WarehouseContainer, error) {
	row := q.db.QueryRow(ctx, getContainerByShortCode, arg.WorkspaceID, arg.ShortCode)
	var i WarehouseContainer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.LocationID,
		&i.Description,
		&i.Capacity,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContainersByLocation = `-- name: ListContainersByLocation :many
SELECT id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.containers
WHERE workspace_id = $1 AND location_id = $2 AND is_archived = false
ORDER BY name
`

type ListContainersByLocationParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	LocationID  uuid.UUID `json:"location_id"`
}

func (q *Queries) ListContainersByLocation(ctx context.Context, arg ListContainersByLocationParams) ([]WarehouseContainer, error) {
	rows, err := q.db.Query(ctx, listContainersByLocation, arg.WorkspaceID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseContainer{}
	for rows.Next() {
		var i WarehouseContainer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.LocationID,
			&i.Description,
			&i.Capacity,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainersByWorkspace = `-- name: ListContainersByWorkspace :many
SELECT id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.containers
WHERE workspace_id = $1 AND is_archived = false
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListContainersByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListContainersByWorkspace(ctx context.Context, arg ListContainersByWorkspaceParams) ([]WarehouseContainer, error) {
	rows, err := q.db.Query(ctx, listContainersByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseContainer{}
	for rows.Next() {
		var i WarehouseContainer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.LocationID,
			&i.Description,
			&i.Capacity,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreContainer = `-- name: RestoreContainer :exec
UPDATE warehouse.containers
SET is_archived = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreContainer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreContainer, id)
	return err
}

const searchContainers = `-- name: SearchContainers :many
SELECT id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.containers
WHERE workspace_id = $1
  AND is_archived = false
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT $3
`

type SearchContainersParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) SearchContainers(ctx context.Context, arg SearchContainersParams) ([]WarehouseContainer, error) {
	rows, err := q.db.Query(ctx, searchContainers, arg.WorkspaceID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseContainer{}
	for rows.Next() {
		var i WarehouseContainer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.LocationID,
			&i.Description,
			&i.Capacity,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainer = `-- name: UpdateContainer :one
UPDATE warehouse.containers
SET name = $2, location_id = $3, description = $4, capacity = $5, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, location_id, description, capacity, short_code, is_archived, search_vector, created_at, updated_at
`

type UpdateContainerParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	LocationID  uuid.UUID `json:"location_id"`
	Description *string   `json:"description"`
	Capacity    *string   `json:"capacity"`
}

func (q *Queries) UpdateContainer(ctx context.Context, arg UpdateContainerParams) (WarehouseContainer, error) {
	row := q.db.QueryRow(ctx, updateContainer,
		arg.ID,
		arg.Name,
		arg.LocationID,
		arg.Description,
		arg.Capacity,
	)
	var i WarehouseContainer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.LocationID,
		&i.Description,
		&i.Capacity,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
