// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleted_records.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldDeletedRecords = `-- name: CleanupOldDeletedRecords :exec
DELETE FROM warehouse.deleted_records
WHERE deleted_at < $1
`

func (q *Queries) CleanupOldDeletedRecords(ctx context.Context, deletedAt time.Time) error {
	_, err := q.db.Exec(ctx, cleanupOldDeletedRecords, deletedAt)
	return err
}

const createDeletedRecord = `-- name: CreateDeletedRecord :one
INSERT INTO warehouse.deleted_records (id, workspace_id, entity_type, entity_id, deleted_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, entity_type, entity_id, deleted_at, deleted_by
`

type CreateDeletedRecordParams struct {
	ID          uuid.UUID                   `json:"id"`
	WorkspaceID uuid.UUID                   `json:"workspace_id"`
	EntityType  WarehouseActivityEntityEnum `json:"entity_type"`
	EntityID    uuid.UUID                   `json:"entity_id"`
	DeletedBy   pgtype.UUID                 `json:"deleted_by"`
}

func (q *Queries) CreateDeletedRecord(ctx context.Context, arg CreateDeletedRecordParams) (WarehouseDeletedRecord, error) {
	row := q.db.QueryRow(ctx, createDeletedRecord,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.DeletedBy,
	)
	var i WarehouseDeletedRecord
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listDeletedSince = `-- name: ListDeletedSince :many
SELECT id, workspace_id, entity_type, entity_id, deleted_at, deleted_by FROM warehouse.deleted_records
WHERE workspace_id = $1 AND deleted_at > $2
ORDER BY deleted_at ASC
`

type ListDeletedSinceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	DeletedAt   time.Time `json:"deleted_at"`
}

func (q *Queries) ListDeletedSince(ctx context.Context, arg ListDeletedSinceParams) ([]WarehouseDeletedRecord, error) {
	rows, err := q.db.Query(ctx, listDeletedSince, arg.WorkspaceID, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseDeletedRecord{}
	for rows.Next() {
		var i WarehouseDeletedRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
