// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const findIdempotencyKey = `-- name: FindIdempotencyKey :one

SELECT entity_id FROM warehouse.idempotency_keys
WHERE workspace_id = $1 AND idempotency_key = $2
`

type FindIdempotencyKeyParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

// Idempotency store (warehouse.idempotency_keys, migration 008). Dedupes
// replayed CREATE requests keyed on (workspace_id, idempotency_key). Used by
// item/container/location Service.Create — see
// internal/domain/warehouse/idempotency/store.go.
func (q *Queries) FindIdempotencyKey(ctx context.Context, arg FindIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findIdempotencyKey, arg.WorkspaceID, arg.IdempotencyKey)
	var entity_id uuid.UUID
	err := row.Scan(&entity_id)
	return entity_id, err
}

const saveIdempotencyKey = `-- name: SaveIdempotencyKey :exec
INSERT INTO warehouse.idempotency_keys (workspace_id, idempotency_key, entity_type, entity_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, idempotency_key) DO NOTHING
`

type SaveIdempotencyKeyParams struct {
	WorkspaceID    uuid.UUID                 `json:"workspace_id"`
	IdempotencyKey string                    `json:"idempotency_key"`
	EntityType     WarehouseFavoriteTypeEnum `json:"entity_type"`
	EntityID       uuid.UUID                 `json:"entity_id"`
}

func (q *Queries) SaveIdempotencyKey(ctx context.Context, arg SaveIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyKey,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}
