// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_photos.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countItemPhotosByItem = `-- name: CountItemPhotosByItem :one
SELECT COUNT(*) FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
`

type CountItemPhotosByItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) CountItemPhotosByItem(ctx context.Context, arg CountItemPhotosByItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemPhotosByItem, arg.ItemID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemPhoto = `-- name: CreateItemPhoto :one
INSERT INTO warehouse.item_photos (
    id, item_id, workspace_id, filename, storage_path, thumbnail_path,
    file_size, mime_type, width, height, display_order, is_primary,
    caption, uploaded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at
`

type CreateItemPhotoParams struct {
	ID            uuid.UUID `json:"id"`
	ItemID        uuid.UUID `json:"item_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	Filename      string    `json:"filename"`
	StoragePath   string    `json:"storage_path"`
	ThumbnailPath string    `json:"thumbnail_path"`
	FileSize      int64     `json:"file_size"`
	MimeType      string    `json:"mime_type"`
	Width         int32     `json:"width"`
	Height        int32     `json:"height"`
	DisplayOrder  int32     `json:"display_order"`
	IsPrimary     bool      `json:"is_primary"`
	Caption       *string   `json:"caption"`
	UploadedBy    uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateItemPhoto(ctx context.Context, arg CreateItemPhotoParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, createItemPhoto,
		arg.ID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.Filename,
		arg.StoragePath,
		arg.ThumbnailPath,
		arg.FileSize,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DisplayOrder,
		arg.IsPrimary,
		arg.Caption,
		arg.UploadedBy,
	)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemPhoto = `-- name: DeleteItemPhoto :exec
DELETE FROM warehouse.item_photos
WHERE id = $1 AND workspace_id = $2
`

type DeleteItemPhotoParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteItemPhoto(ctx context.Context, arg DeleteItemPhotoParams) error {
	_, err := q.db.Exec(ctx, deleteItemPhoto, arg.ID, arg.WorkspaceID)
	return err
}

const deleteItemPhotosByItem = `-- name: DeleteItemPhotosByItem :exec
DELETE FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
`

type DeleteItemPhotosByItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteItemPhotosByItem(ctx context.Context, arg DeleteItemPhotosByItemParams) error {
	_, err := q.db.Exec(ctx, deleteItemPhotosByItem, arg.ItemID, arg.WorkspaceID)
	return err
}

const getItemPhoto = `-- name: GetItemPhoto :one
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at FROM warehouse.item_photos
WHERE id = $1
`

func (q *Queries) GetItemPhoto(ctx context.Context, id uuid.UUID) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, getItemPhoto, id)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemPhotoByID = `-- name: GetItemPhotoByID :one
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at FROM warehouse.item_photos
WHERE id = $1 AND workspace_id = $2
`

type GetItemPhotoByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetItemPhotoByID(ctx context.Context, arg GetItemPhotoByIDParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, getItemPhotoByID, arg.ID, arg.WorkspaceID)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextDisplayOrder = `-- name: GetNextDisplayOrder :one
SELECT COALESCE(MAX(display_order) + 1, 0) as next_order
FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
`

type GetNextDisplayOrderParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetNextDisplayOrder(ctx context.Context, arg GetNextDisplayOrderParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getNextDisplayOrder, arg.ItemID, arg.WorkspaceID)
	var next_order interface{}
	err := row.Scan(&next_order)
	return next_order, err
}

const getPrimaryItemPhoto = `-- name: GetPrimaryItemPhoto :one
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2 AND is_primary = true
LIMIT 1
`

type GetPrimaryItemPhotoParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetPrimaryItemPhoto(ctx context.Context, arg GetPrimaryItemPhotoParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, getPrimaryItemPhoto, arg.ItemID, arg.WorkspaceID)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemPhotosByItem = `-- name: ListItemPhotosByItem :many
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
ORDER BY display_order ASC, created_at ASC
`

type ListItemPhotosByItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListItemPhotosByItem(ctx context.Context, arg ListItemPhotosByItemParams) ([]WarehouseItemPhoto, error) {
	rows, err := q.db.Query(ctx, listItemPhotosByItem, arg.ItemID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseItemPhoto{}
	for rows.Next() {
		var i WarehouseItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WorkspaceID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DisplayOrder,
			&i.IsPrimary,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemPhotoAsPrimary = `-- name: SetItemPhotoAsPrimary :exec
UPDATE warehouse.item_photos
SET is_primary = true, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetItemPhotoAsPrimaryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SetItemPhotoAsPrimary(ctx context.Context, arg SetItemPhotoAsPrimaryParams) error {
	_, err := q.db.Exec(ctx, setItemPhotoAsPrimary, arg.ID, arg.WorkspaceID)
	return err
}

const unsetPrimaryPhotosForItem = `-- name: UnsetPrimaryPhotosForItem :exec
UPDATE warehouse.item_photos
SET is_primary = false, updated_at = now()
WHERE item_id = $1 AND workspace_id = $2
`

type UnsetPrimaryPhotosForItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UnsetPrimaryPhotosForItem(ctx context.Context, arg UnsetPrimaryPhotosForItemParams) error {
	_, err := q.db.Exec(ctx, unsetPrimaryPhotosForItem, arg.ItemID, arg.WorkspaceID)
	return err
}

const updateItemPhoto = `-- name: UpdateItemPhoto :one
UPDATE warehouse.item_photos
SET
    filename = COALESCE($1, filename),
    caption = COALESCE($2, caption),
    is_primary = COALESCE($3, is_primary),
    display_order = COALESCE($4, display_order),
    updated_at = now()
WHERE id = $5
RETURNING id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at
`

type UpdateItemPhotoParams struct {
	Filename     *string   `json:"filename"`
	Caption      *string   `json:"caption"`
	IsPrimary    *bool     `json:"is_primary"`
	DisplayOrder *int32    `json:"display_order"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateItemPhoto(ctx context.Context, arg UpdateItemPhotoParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, updateItemPhoto,
		arg.Filename,
		arg.Caption,
		arg.IsPrimary,
		arg.DisplayOrder,
		arg.ID,
	)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemPhotoDisplayOrder = `-- name: UpdateItemPhotoDisplayOrder :exec
UPDATE warehouse.item_photos
SET display_order = $2, updated_at = now()
WHERE id = $1
`

type UpdateItemPhotoDisplayOrderParams struct {
	ID           uuid.UUID `json:"id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) UpdateItemPhotoDisplayOrder(ctx context.Context, arg UpdateItemPhotoDisplayOrderParams) error {
	_, err := q.db.Exec(ctx, updateItemPhotoDisplayOrder, arg.ID, arg.DisplayOrder)
	return err
}
