// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_photos.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bulkDeleteItemPhotos = `-- name: BulkDeleteItemPhotos :exec
DELETE FROM warehouse.item_photos
WHERE id = ANY($1::UUID[]) AND workspace_id = $2
`

type BulkDeleteItemPhotosParams struct {
	Ids         []uuid.UUID `json:"ids"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
}

// Delete multiple photos by ID array (workspace check ensures security)
func (q *Queries) BulkDeleteItemPhotos(ctx context.Context, arg BulkDeleteItemPhotosParams) error {
	_, err := q.db.Exec(ctx, bulkDeleteItemPhotos, arg.Ids, arg.WorkspaceID)
	return err
}

const countItemPhotosByItem = `-- name: CountItemPhotosByItem :one
SELECT COUNT(*) FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
`

type CountItemPhotosByItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) CountItemPhotosByItem(ctx context.Context, arg CountItemPhotosByItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemPhotosByItem, arg.ItemID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemPhoto = `-- name: CreateItemPhoto :one
INSERT INTO warehouse.item_photos (
    id, item_id, workspace_id, filename, storage_path, thumbnail_path,
    file_size, mime_type, width, height, display_order, is_primary,
    caption, uploaded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash
`

type CreateItemPhotoParams struct {
	ID            uuid.UUID `json:"id"`
	ItemID        uuid.UUID `json:"item_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	Filename      string    `json:"filename"`
	StoragePath   string    `json:"storage_path"`
	ThumbnailPath string    `json:"thumbnail_path"`
	FileSize      int64     `json:"file_size"`
	MimeType      string    `json:"mime_type"`
	Width         int32     `json:"width"`
	Height        int32     `json:"height"`
	DisplayOrder  int32     `json:"display_order"`
	IsPrimary     bool      `json:"is_primary"`
	Caption       *string   `json:"caption"`
	UploadedBy    uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateItemPhoto(ctx context.Context, arg CreateItemPhotoParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, createItemPhoto,
		arg.ID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.Filename,
		arg.StoragePath,
		arg.ThumbnailPath,
		arg.FileSize,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DisplayOrder,
		arg.IsPrimary,
		arg.Caption,
		arg.UploadedBy,
	)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
	)
	return i, err
}

const deleteItemPhoto = `-- name: DeleteItemPhoto :exec
DELETE FROM warehouse.item_photos
WHERE id = $1 AND workspace_id = $2
`

type DeleteItemPhotoParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteItemPhoto(ctx context.Context, arg DeleteItemPhotoParams) error {
	_, err := q.db.Exec(ctx, deleteItemPhoto, arg.ID, arg.WorkspaceID)
	return err
}

const deleteItemPhotosByItem = `-- name: DeleteItemPhotosByItem :exec
DELETE FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
`

type DeleteItemPhotosByItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteItemPhotosByItem(ctx context.Context, arg DeleteItemPhotosByItemParams) error {
	_, err := q.db.Exec(ctx, deleteItemPhotosByItem, arg.ItemID, arg.WorkspaceID)
	return err
}

const getItemPhoto = `-- name: GetItemPhoto :one
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE id = $1
`

func (q *Queries) GetItemPhoto(ctx context.Context, id uuid.UUID) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, getItemPhoto, id)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
	)
	return i, err
}

const getItemPhotoByID = `-- name: GetItemPhotoByID :one
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE id = $1 AND workspace_id = $2
`

type GetItemPhotoByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetItemPhotoByID(ctx context.Context, arg GetItemPhotoByIDParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, getItemPhotoByID, arg.ID, arg.WorkspaceID)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
	)
	return i, err
}

const getItemPhotoForProcessing = `-- name: GetItemPhotoForProcessing :one
SELECT ip.id, ip.item_id, ip.workspace_id, ip.filename, ip.storage_path, ip.thumbnail_path, ip.file_size, ip.mime_type, ip.width, ip.height, ip.display_order, ip.is_primary, ip.caption, ip.uploaded_by, ip.created_at, ip.updated_at, ip.thumbnail_status, ip.thumbnail_small_path, ip.thumbnail_medium_path, ip.thumbnail_large_path, ip.thumbnail_attempts, ip.thumbnail_error, ip.perceptual_hash, i.workspace_id as item_workspace_id
FROM warehouse.item_photos ip
JOIN warehouse.items i ON i.id = ip.item_id
WHERE ip.id = $1
`

type GetItemPhotoForProcessingRow struct {
	ID                  uuid.UUID `json:"id"`
	ItemID              uuid.UUID `json:"item_id"`
	WorkspaceID         uuid.UUID `json:"workspace_id"`
	Filename            string    `json:"filename"`
	StoragePath         string    `json:"storage_path"`
	ThumbnailPath       string    `json:"thumbnail_path"`
	FileSize            int64     `json:"file_size"`
	MimeType            string    `json:"mime_type"`
	Width               int32     `json:"width"`
	Height              int32     `json:"height"`
	DisplayOrder        int32     `json:"display_order"`
	IsPrimary           bool      `json:"is_primary"`
	Caption             *string   `json:"caption"`
	UploadedBy          uuid.UUID `json:"uploaded_by"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	ThumbnailStatus     string    `json:"thumbnail_status"`
	ThumbnailSmallPath  *string   `json:"thumbnail_small_path"`
	ThumbnailMediumPath *string   `json:"thumbnail_medium_path"`
	ThumbnailLargePath  *string   `json:"thumbnail_large_path"`
	ThumbnailAttempts   int32     `json:"thumbnail_attempts"`
	ThumbnailError      *string   `json:"thumbnail_error"`
	PerceptualHash      *int64    `json:"perceptual_hash"`
	ItemWorkspaceID     uuid.UUID `json:"item_workspace_id"`
}

// Get photo with workspace for background job processing
func (q *Queries) GetItemPhotoForProcessing(ctx context.Context, id uuid.UUID) (GetItemPhotoForProcessingRow, error) {
	row := q.db.QueryRow(ctx, getItemPhotoForProcessing, id)
	var i GetItemPhotoForProcessingRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
		&i.ItemWorkspaceID,
	)
	return i, err
}

const getItemPhotosByIDs = `-- name: GetItemPhotosByIDs :many

SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE id = ANY($1::UUID[]) AND workspace_id = $2
ORDER BY display_order ASC
`

type GetItemPhotosByIDsParams struct {
	Ids         []uuid.UUID `json:"ids"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
}

// Bulk operations queries
// Get multiple photos by ID array with workspace verification
func (q *Queries) GetItemPhotosByIDs(ctx context.Context, arg GetItemPhotosByIDsParams) ([]WarehouseItemPhoto, error) {
	rows, err := q.db.Query(ctx, getItemPhotosByIDs, arg.Ids, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseItemPhoto{}
	for rows.Next() {
		var i WarehouseItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WorkspaceID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DisplayOrder,
			&i.IsPrimary,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailStatus,
			&i.ThumbnailSmallPath,
			&i.ThumbnailMediumPath,
			&i.ThumbnailLargePath,
			&i.ThumbnailAttempts,
			&i.ThumbnailError,
			&i.PerceptualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemPhotosWithHashes = `-- name: GetItemPhotosWithHashes :many
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE item_id = $1
  AND workspace_id = $2
  AND perceptual_hash IS NOT NULL
ORDER BY display_order ASC
`

type GetItemPhotosWithHashesParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// Get photos with perceptual hashes for a specific item
func (q *Queries) GetItemPhotosWithHashes(ctx context.Context, arg GetItemPhotosWithHashesParams) ([]WarehouseItemPhoto, error) {
	rows, err := q.db.Query(ctx, getItemPhotosWithHashes, arg.ItemID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseItemPhoto{}
	for rows.Next() {
		var i WarehouseItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WorkspaceID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DisplayOrder,
			&i.IsPrimary,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailStatus,
			&i.ThumbnailSmallPath,
			&i.ThumbnailMediumPath,
			&i.ThumbnailLargePath,
			&i.ThumbnailAttempts,
			&i.ThumbnailError,
			&i.PerceptualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextDisplayOrder = `-- name: GetNextDisplayOrder :one
SELECT COALESCE(MAX(display_order) + 1, 0) as next_order
FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
`

type GetNextDisplayOrderParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetNextDisplayOrder(ctx context.Context, arg GetNextDisplayOrderParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getNextDisplayOrder, arg.ItemID, arg.WorkspaceID)
	var next_order interface{}
	err := row.Scan(&next_order)
	return next_order, err
}

const getPhotosWithHashes = `-- name: GetPhotosWithHashes :many
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE workspace_id = $1
  AND perceptual_hash IS NOT NULL
ORDER BY created_at DESC
`

// Get photos with perceptual hashes for duplicate detection within a workspace
func (q *Queries) GetPhotosWithHashes(ctx context.Context, workspaceID uuid.UUID) ([]WarehouseItemPhoto, error) {
	rows, err := q.db.Query(ctx, getPhotosWithHashes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseItemPhoto{}
	for rows.Next() {
		var i WarehouseItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WorkspaceID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DisplayOrder,
			&i.IsPrimary,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailStatus,
			&i.ThumbnailSmallPath,
			&i.ThumbnailMediumPath,
			&i.ThumbnailLargePath,
			&i.ThumbnailAttempts,
			&i.ThumbnailError,
			&i.PerceptualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryItemPhoto = `-- name: GetPrimaryItemPhoto :one
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2 AND is_primary = true
LIMIT 1
`

type GetPrimaryItemPhotoParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetPrimaryItemPhoto(ctx context.Context, arg GetPrimaryItemPhotoParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, getPrimaryItemPhoto, arg.ItemID, arg.WorkspaceID)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
	)
	return i, err
}

const listItemPhotosByItem = `-- name: ListItemPhotosByItem :many
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE item_id = $1 AND workspace_id = $2
ORDER BY display_order ASC, created_at ASC
`

type ListItemPhotosByItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListItemPhotosByItem(ctx context.Context, arg ListItemPhotosByItemParams) ([]WarehouseItemPhoto, error) {
	rows, err := q.db.Query(ctx, listItemPhotosByItem, arg.ItemID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseItemPhoto{}
	for rows.Next() {
		var i WarehouseItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WorkspaceID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DisplayOrder,
			&i.IsPrimary,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailStatus,
			&i.ThumbnailSmallPath,
			&i.ThumbnailMediumPath,
			&i.ThumbnailLargePath,
			&i.ThumbnailAttempts,
			&i.ThumbnailError,
			&i.PerceptualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingThumbnails = `-- name: ListPendingThumbnails :many
SELECT id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash FROM warehouse.item_photos
WHERE thumbnail_status IN ('pending', 'processing')
  AND thumbnail_attempts < 5
ORDER BY created_at ASC
LIMIT $1
`

// Find photos needing thumbnail processing (used by background worker)
func (q *Queries) ListPendingThumbnails(ctx context.Context, limit int32) ([]WarehouseItemPhoto, error) {
	rows, err := q.db.Query(ctx, listPendingThumbnails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseItemPhoto{}
	for rows.Next() {
		var i WarehouseItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.WorkspaceID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DisplayOrder,
			&i.IsPrimary,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailStatus,
			&i.ThumbnailSmallPath,
			&i.ThumbnailMediumPath,
			&i.ThumbnailLargePath,
			&i.ThumbnailAttempts,
			&i.ThumbnailError,
			&i.PerceptualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemPhotoAsPrimary = `-- name: SetItemPhotoAsPrimary :exec
UPDATE warehouse.item_photos
SET is_primary = true, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetItemPhotoAsPrimaryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SetItemPhotoAsPrimary(ctx context.Context, arg SetItemPhotoAsPrimaryParams) error {
	_, err := q.db.Exec(ctx, setItemPhotoAsPrimary, arg.ID, arg.WorkspaceID)
	return err
}

const unsetPrimaryPhotosForItem = `-- name: UnsetPrimaryPhotosForItem :exec
UPDATE warehouse.item_photos
SET is_primary = false, updated_at = now()
WHERE item_id = $1 AND workspace_id = $2
`

type UnsetPrimaryPhotosForItemParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UnsetPrimaryPhotosForItem(ctx context.Context, arg UnsetPrimaryPhotosForItemParams) error {
	_, err := q.db.Exec(ctx, unsetPrimaryPhotosForItem, arg.ItemID, arg.WorkspaceID)
	return err
}

const updateItemPhoto = `-- name: UpdateItemPhoto :one
UPDATE warehouse.item_photos
SET
    filename = COALESCE($1, filename),
    caption = COALESCE($2, caption),
    is_primary = COALESCE($3, is_primary),
    display_order = COALESCE($4, display_order),
    updated_at = now()
WHERE id = $5
RETURNING id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash
`

type UpdateItemPhotoParams struct {
	Filename     *string   `json:"filename"`
	Caption      *string   `json:"caption"`
	IsPrimary    *bool     `json:"is_primary"`
	DisplayOrder *int32    `json:"display_order"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateItemPhoto(ctx context.Context, arg UpdateItemPhotoParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, updateItemPhoto,
		arg.Filename,
		arg.Caption,
		arg.IsPrimary,
		arg.DisplayOrder,
		arg.ID,
	)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
	)
	return i, err
}

const updateItemPhotoDisplayOrder = `-- name: UpdateItemPhotoDisplayOrder :exec
UPDATE warehouse.item_photos
SET display_order = $2, updated_at = now()
WHERE id = $1
`

type UpdateItemPhotoDisplayOrderParams struct {
	ID           uuid.UUID `json:"id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) UpdateItemPhotoDisplayOrder(ctx context.Context, arg UpdateItemPhotoDisplayOrderParams) error {
	_, err := q.db.Exec(ctx, updateItemPhotoDisplayOrder, arg.ID, arg.DisplayOrder)
	return err
}

const updatePerceptualHash = `-- name: UpdatePerceptualHash :exec
UPDATE warehouse.item_photos
SET perceptual_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdatePerceptualHashParams struct {
	PerceptualHash *int64    `json:"perceptual_hash"`
	ID             uuid.UUID `json:"id"`
}

// Set perceptual hash after upload processing
func (q *Queries) UpdatePerceptualHash(ctx context.Context, arg UpdatePerceptualHashParams) error {
	_, err := q.db.Exec(ctx, updatePerceptualHash, arg.PerceptualHash, arg.ID)
	return err
}

const updatePhotoCaption = `-- name: UpdatePhotoCaption :exec
UPDATE warehouse.item_photos
SET caption = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3
`

type UpdatePhotoCaptionParams struct {
	Caption     *string   `json:"caption"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// Update caption for single photo (used in bulk caption updates)
func (q *Queries) UpdatePhotoCaption(ctx context.Context, arg UpdatePhotoCaptionParams) error {
	_, err := q.db.Exec(ctx, updatePhotoCaption, arg.Caption, arg.ID, arg.WorkspaceID)
	return err
}

const updateThumbnailPaths = `-- name: UpdateThumbnailPaths :one
UPDATE warehouse.item_photos
SET thumbnail_small_path = $2,
    thumbnail_medium_path = $3,
    thumbnail_large_path = $4,
    thumbnail_status = 'complete',
    thumbnail_error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, item_id, workspace_id, filename, storage_path, thumbnail_path, file_size, mime_type, width, height, display_order, is_primary, caption, uploaded_by, created_at, updated_at, thumbnail_status, thumbnail_small_path, thumbnail_medium_path, thumbnail_large_path, thumbnail_attempts, thumbnail_error, perceptual_hash
`

type UpdateThumbnailPathsParams struct {
	ID                  uuid.UUID `json:"id"`
	ThumbnailSmallPath  *string   `json:"thumbnail_small_path"`
	ThumbnailMediumPath *string   `json:"thumbnail_medium_path"`
	ThumbnailLargePath  *string   `json:"thumbnail_large_path"`
}

// Set all thumbnail paths and mark as complete
func (q *Queries) UpdateThumbnailPaths(ctx context.Context, arg UpdateThumbnailPathsParams) (WarehouseItemPhoto, error) {
	row := q.db.QueryRow(ctx, updateThumbnailPaths,
		arg.ID,
		arg.ThumbnailSmallPath,
		arg.ThumbnailMediumPath,
		arg.ThumbnailLargePath,
	)
	var i WarehouseItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.Filename,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DisplayOrder,
		&i.IsPrimary,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailStatus,
		&i.ThumbnailSmallPath,
		&i.ThumbnailMediumPath,
		&i.ThumbnailLargePath,
		&i.ThumbnailAttempts,
		&i.ThumbnailError,
		&i.PerceptualHash,
	)
	return i, err
}

const updateThumbnailStatus = `-- name: UpdateThumbnailStatus :exec

UPDATE warehouse.item_photos
SET thumbnail_status = $2,
    thumbnail_attempts = thumbnail_attempts + 1,
    thumbnail_error = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateThumbnailStatusParams struct {
	ID              uuid.UUID `json:"id"`
	ThumbnailStatus string    `json:"thumbnail_status"`
	ThumbnailError  *string   `json:"thumbnail_error"`
}

// Thumbnail processing queries
// Update thumbnail status and increment attempts counter
func (q *Queries) UpdateThumbnailStatus(ctx context.Context, arg UpdateThumbnailStatusParams) error {
	_, err := q.db.Exec(ctx, updateThumbnailStatus, arg.ID, arg.ThumbnailStatus, arg.ThumbnailError)
	return err
}
