// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveLocation = `-- name: ArchiveLocation :exec
UPDATE warehouse.locations
SET is_archived = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveLocation, id)
	return err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO warehouse.locations (id, workspace_id, name, parent_location, description, short_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at
`

type CreateLocationParams struct {
	ID             uuid.UUID   `json:"id"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	Name           string      `json:"name"`
	ParentLocation pgtype.UUID `json:"parent_location"`
	Description    *string     `json:"description"`
	ShortCode      string      `json:"short_code"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (WarehouseLocation, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ParentLocation,
		arg.Description,
		arg.ShortCode,
	)
	var i WarehouseLocation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentLocation,
		&i.Description,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM warehouse.locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.locations
WHERE id = $1 AND workspace_id = $2
`

type GetLocationParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (WarehouseLocation, error) {
	row := q.db.QueryRow(ctx, getLocation, arg.ID, arg.WorkspaceID)
	var i WarehouseLocation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentLocation,
		&i.Description,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationByShortCode = `-- name: GetLocationByShortCode :one
SELECT id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.locations
WHERE workspace_id = $1 AND short_code = $2
`

type GetLocationByShortCodeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ShortCode   string    `json:"short_code"`
}

func (q *Queries) GetLocationByShortCode(ctx context.Context, arg GetLocationByShortCodeParams) (WarehouseLocation, error) {
	row := q.db.QueryRow(ctx, getLocationByShortCode, arg.WorkspaceID, arg.ShortCode)
	var i WarehouseLocation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentLocation,
		&i.Description,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.locations
WHERE workspace_id = $1 AND is_archived = false
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListLocationsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]WarehouseLocation, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseLocation{}
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentLocation,
			&i.Description,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByParent = `-- name: ListLocationsByParent :many
SELECT id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.locations
WHERE workspace_id = $1 AND parent_location = $2 AND is_archived = false
ORDER BY name
`

type ListLocationsByParentParams struct {
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	ParentLocation pgtype.UUID `json:"parent_location"`
}

func (q *Queries) ListLocationsByParent(ctx context.Context, arg ListLocationsByParentParams) ([]WarehouseLocation, error) {
	rows, err := q.db.Query(ctx, listLocationsByParent, arg.WorkspaceID, arg.ParentLocation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseLocation{}
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentLocation,
			&i.Description,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootLocations = `-- name: ListRootLocations :many
SELECT id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.locations
WHERE workspace_id = $1 AND parent_location IS NULL AND is_archived = false
ORDER BY name
`

func (q *Queries) ListRootLocations(ctx context.Context, workspaceID uuid.UUID) ([]WarehouseLocation, error) {
	rows, err := q.db.Query(ctx, listRootLocations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseLocation{}
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentLocation,
			&i.Description,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLocation = `-- name: RestoreLocation :exec
UPDATE warehouse.locations
SET is_archived = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreLocation, id)
	return err
}

const searchLocations = `-- name: SearchLocations :many
SELECT id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at FROM warehouse.locations
WHERE workspace_id = $1
  AND is_archived = false
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT $3
`

type SearchLocationsParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) SearchLocations(ctx context.Context, arg SearchLocationsParams) ([]WarehouseLocation, error) {
	rows, err := q.db.Query(ctx, searchLocations, arg.WorkspaceID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseLocation{}
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentLocation,
			&i.Description,
			&i.ShortCode,
			&i.IsArchived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shortCodeExists = `-- name: ShortCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM warehouse.locations
    WHERE workspace_id = $1 AND short_code = $2
)
`

type ShortCodeExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ShortCode   string    `json:"short_code"`
}

func (q *Queries) ShortCodeExists(ctx context.Context, arg ShortCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, shortCodeExists, arg.WorkspaceID, arg.ShortCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE warehouse.locations
SET name = $2, parent_location = $3, description = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, parent_location, description, short_code, is_archived, search_vector, created_at, updated_at
`

type UpdateLocationParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	ParentLocation pgtype.UUID `json:"parent_location"`
	Description    *string     `json:"description"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (WarehouseLocation, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.ParentLocation,
		arg.Description,
	)
	var i WarehouseLocation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentLocation,
		&i.Description,
		&i.ShortCode,
		&i.IsArchived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
