// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance_schedules.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMaintenanceSchedulesByWorkspace = `-- name: CountMaintenanceSchedulesByWorkspace :one
SELECT COUNT(*) FROM warehouse.maintenance_schedules
WHERE workspace_id = $1
`

func (q *Queries) CountMaintenanceSchedulesByWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceSchedulesByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenanceSchedule = `-- name: CreateMaintenanceSchedule :one
INSERT INTO warehouse.maintenance_schedules (
    id, workspace_id, inventory_id, title, notes, interval_days, next_due, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, inventory_id, title, notes, interval_days, next_due, last_completed_at, is_active, created_at, updated_at
`

type CreateMaintenanceScheduleParams struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	InventoryID  uuid.UUID   `json:"inventory_id"`
	Title        string      `json:"title"`
	Notes        *string     `json:"notes"`
	IntervalDays int32       `json:"interval_days"`
	NextDue      pgtype.Date `json:"next_due"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateMaintenanceSchedule(ctx context.Context, arg CreateMaintenanceScheduleParams) (WarehouseMaintenanceSchedule, error) {
	row := q.db.QueryRow(ctx, createMaintenanceSchedule,
		arg.ID,
		arg.WorkspaceID,
		arg.InventoryID,
		arg.Title,
		arg.Notes,
		arg.IntervalDays,
		arg.NextDue,
		arg.IsActive,
	)
	var i WarehouseMaintenanceSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InventoryID,
		&i.Title,
		&i.Notes,
		&i.IntervalDays,
		&i.NextDue,
		&i.LastCompletedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenanceSchedule = `-- name: DeleteMaintenanceSchedule :exec
DELETE FROM warehouse.maintenance_schedules
WHERE id = $1 AND workspace_id = $2
`

type DeleteMaintenanceScheduleParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteMaintenanceSchedule(ctx context.Context, arg DeleteMaintenanceScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceSchedule, arg.ID, arg.WorkspaceID)
	return err
}

const getMaintenanceSchedule = `-- name: GetMaintenanceSchedule :one
SELECT id, workspace_id, inventory_id, title, notes, interval_days, next_due, last_completed_at, is_active, created_at, updated_at FROM warehouse.maintenance_schedules
WHERE id = $1 AND workspace_id = $2
`

type GetMaintenanceScheduleParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetMaintenanceSchedule(ctx context.Context, arg GetMaintenanceScheduleParams) (WarehouseMaintenanceSchedule, error) {
	row := q.db.QueryRow(ctx, getMaintenanceSchedule, arg.ID, arg.WorkspaceID)
	var i WarehouseMaintenanceSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InventoryID,
		&i.Title,
		&i.Notes,
		&i.IntervalDays,
		&i.NextDue,
		&i.LastCompletedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaintenanceSchedulesByInventory = `-- name: ListMaintenanceSchedulesByInventory :many
SELECT id, workspace_id, inventory_id, title, notes, interval_days, next_due, last_completed_at, is_active, created_at, updated_at FROM warehouse.maintenance_schedules
WHERE workspace_id = $1 AND inventory_id = $2
ORDER BY next_due, id
`

type ListMaintenanceSchedulesByInventoryParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	InventoryID uuid.UUID `json:"inventory_id"`
}

func (q *Queries) ListMaintenanceSchedulesByInventory(ctx context.Context, arg ListMaintenanceSchedulesByInventoryParams) ([]WarehouseMaintenanceSchedule, error) {
	rows, err := q.db.Query(ctx, listMaintenanceSchedulesByInventory, arg.WorkspaceID, arg.InventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseMaintenanceSchedule{}
	for rows.Next() {
		var i WarehouseMaintenanceSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InventoryID,
			&i.Title,
			&i.Notes,
			&i.IntervalDays,
			&i.NextDue,
			&i.LastCompletedAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceSchedulesByWorkspace = `-- name: ListMaintenanceSchedulesByWorkspace :many
SELECT id, workspace_id, inventory_id, title, notes, interval_days, next_due, last_completed_at, is_active, created_at, updated_at FROM warehouse.maintenance_schedules
WHERE workspace_id = $1
ORDER BY next_due, id
LIMIT $2 OFFSET $3
`

type ListMaintenanceSchedulesByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListMaintenanceSchedulesByWorkspace(ctx context.Context, arg ListMaintenanceSchedulesByWorkspaceParams) ([]WarehouseMaintenanceSchedule, error) {
	rows, err := q.db.Query(ctx, listMaintenanceSchedulesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseMaintenanceSchedule{}
	for rows.Next() {
		var i WarehouseMaintenanceSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InventoryID,
			&i.Title,
			&i.Notes,
			&i.IntervalDays,
			&i.NextDue,
			&i.LastCompletedAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceSchedulesDue = `-- name: ListMaintenanceSchedulesDue :many
SELECT ms.id, ms.workspace_id, ms.inventory_id, ms.title, ms.notes, ms.interval_days, ms.next_due, ms.last_completed_at, ms.is_active, ms.created_at, ms.updated_at, it.name AS item_name, inv.item_id
FROM warehouse.maintenance_schedules ms
JOIN warehouse.inventory inv ON ms.inventory_id = inv.id AND inv.workspace_id = ms.workspace_id
JOIN warehouse.items it ON inv.item_id = it.id AND it.workspace_id = inv.workspace_id
WHERE ms.workspace_id = $1
  AND ms.is_active = true
  AND ms.next_due <= $2
ORDER BY ms.next_due, ms.id
`

type ListMaintenanceSchedulesDueParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	NextDue     pgtype.Date `json:"next_due"`
}

type ListMaintenanceSchedulesDueRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	InventoryID     uuid.UUID          `json:"inventory_id"`
	Title           string             `json:"title"`
	Notes           *string            `json:"notes"`
	IntervalDays    int32              `json:"interval_days"`
	NextDue         pgtype.Date        `json:"next_due"`
	LastCompletedAt pgtype.Timestamptz `json:"last_completed_at"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ItemName        string             `json:"item_name"`
	ItemID          uuid.UUID          `json:"item_id"`
}

// Active schedules due on or before the cutoff date (includes overdue),
// decorated with the item name for reminder/widget display. Uses the
// (workspace_id, next_due) index.
func (q *Queries) ListMaintenanceSchedulesDue(ctx context.Context, arg ListMaintenanceSchedulesDueParams) ([]ListMaintenanceSchedulesDueRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceSchedulesDue, arg.WorkspaceID, arg.NextDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceSchedulesDueRow{}
	for rows.Next() {
		var i ListMaintenanceSchedulesDueRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InventoryID,
			&i.Title,
			&i.Notes,
			&i.IntervalDays,
			&i.NextDue,
			&i.LastCompletedAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemName,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceSchedule = `-- name: UpdateMaintenanceSchedule :one
UPDATE warehouse.maintenance_schedules
SET title = $3,
    notes = $4,
    interval_days = $5,
    next_due = $6,
    last_completed_at = $7,
    is_active = $8,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, inventory_id, title, notes, interval_days, next_due, last_completed_at, is_active, created_at, updated_at
`

type UpdateMaintenanceScheduleParams struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Title           string             `json:"title"`
	Notes           *string            `json:"notes"`
	IntervalDays    int32              `json:"interval_days"`
	NextDue         pgtype.Date        `json:"next_due"`
	LastCompletedAt pgtype.Timestamptz `json:"last_completed_at"`
	IsActive        bool               `json:"is_active"`
}

// Full-row update used by the repository Save path. last_completed_at and
// next_due are included so completions (which advance next_due and stamp
// last_completed_at via the domain entity) persist through the same query.
func (q *Queries) UpdateMaintenanceSchedule(ctx context.Context, arg UpdateMaintenanceScheduleParams) (WarehouseMaintenanceSchedule, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceSchedule,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Notes,
		arg.IntervalDays,
		arg.NextDue,
		arg.LastCompletedAt,
		arg.IsActive,
	)
	var i WarehouseMaintenanceSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InventoryID,
		&i.Title,
		&i.Notes,
		&i.IntervalDays,
		&i.NextDue,
		&i.LastCompletedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
