// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT COUNT(*) FROM auth.notifications
WHERE user_id = $1
`

func (q *Queries) CountNotificationsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO auth.notifications (id, user_id, workspace_id, notification_type, title, message, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, workspace_id, notification_type, title, message, is_read, read_at, metadata, created_at
`

type CreateNotificationParams struct {
	ID               uuid.UUID                `json:"id"`
	UserID           uuid.UUID                `json:"user_id"`
	WorkspaceID      pgtype.UUID              `json:"workspace_id"`
	NotificationType AuthNotificationTypeEnum `json:"notification_type"`
	Title            string                   `json:"title"`
	Message          string                   `json:"message"`
	Metadata         []byte                   `json:"metadata"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (AuthNotification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.NotificationType,
		arg.Title,
		arg.Message,
		arg.Metadata,
	)
	var i AuthNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.NotificationType,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, workspace_id, notification_type, title, message, is_read, read_at, metadata, created_at FROM auth.notifications WHERE id = $1 AND user_id = $2
`

type GetNotificationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (AuthNotification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.UserID)
	var i AuthNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.NotificationType,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM auth.notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, workspace_id, notification_type, title, message, is_read, read_at, metadata, created_at FROM auth.notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]AuthNotification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthNotification{}
	for rows.Next() {
		var i AuthNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.NotificationType,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ReadAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, workspace_id, notification_type, title, message, is_read, read_at, metadata, created_at FROM auth.notifications
WHERE user_id = $1 AND is_read = false
ORDER BY created_at DESC
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID uuid.UUID) ([]AuthNotification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthNotification{}
	for rows.Next() {
		var i AuthNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.NotificationType,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ReadAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE auth.notifications
SET is_read = true, read_at = now()
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE auth.notifications
SET is_read = true, read_at = now()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
