// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_accounts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOAuthAccountsByUser = `-- name: CountOAuthAccountsByUser :one
SELECT COUNT(*) FROM auth.user_oauth_accounts WHERE user_id = $1
`

func (q *Queries) CountOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOAuthAccountsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO auth.user_oauth_accounts (user_id, provider, provider_user_id, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_user_id, email, display_name, avatar_url, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	Email          *string   `json:"email"`
	DisplayName    *string   `json:"display_name"`
	AvatarUrl      *string   `json:"avatar_url"`
}

type CreateOAuthAccountRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          *string            `json:"email"`
	DisplayName    *string            `json:"display_name"`
	AvatarUrl      *string            `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (CreateOAuthAccountRow, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i CreateOAuthAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthAccountByProvider = `-- name: DeleteOAuthAccountByProvider :exec
DELETE FROM auth.user_oauth_accounts
WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthAccountByProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteOAuthAccountByProvider(ctx context.Context, arg DeleteOAuthAccountByProviderParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccountByProvider, arg.UserID, arg.Provider)
	return err
}

const getOAuthAccountByProviderAndID = `-- name: GetOAuthAccountByProviderAndID :one
SELECT id, user_id, provider, provider_user_id, email, display_name, avatar_url, created_at, updated_at
FROM auth.user_oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountByProviderAndIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

type GetOAuthAccountByProviderAndIDRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          *string            `json:"email"`
	DisplayName    *string            `json:"display_name"`
	AvatarUrl      *string            `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOAuthAccountByProviderAndID(ctx context.Context, arg GetOAuthAccountByProviderAndIDParams) (GetOAuthAccountByProviderAndIDRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByProviderAndID, arg.Provider, arg.ProviderUserID)
	var i GetOAuthAccountByProviderAndIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthAccountsByUser = `-- name: ListOAuthAccountsByUser :many
SELECT id, user_id, provider, provider_user_id, email, display_name, avatar_url, created_at, updated_at
FROM auth.user_oauth_accounts
WHERE user_id = $1
ORDER BY created_at
`

type ListOAuthAccountsByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          *string            `json:"email"`
	DisplayName    *string            `json:"display_name"`
	AvatarUrl      *string            `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) ([]ListOAuthAccountsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOAuthAccountsByUserRow{}
	for rows.Next() {
		var i ListOAuthAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
