// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paperless_settings.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkspacePaperlessSettings = `-- name: DeleteWorkspacePaperlessSettings :exec
DELETE FROM auth.workspace_paperless_settings
WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspacePaperlessSettings(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspacePaperlessSettings, workspaceID)
	return err
}

const getWorkspacePaperlessSettings = `-- name: GetWorkspacePaperlessSettings :one
SELECT id, workspace_id, base_url, api_token_encrypted, sync_tags_enabled, is_enabled, last_sync_at, created_at, updated_at FROM auth.workspace_paperless_settings
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspacePaperlessSettings(ctx context.Context, workspaceID uuid.UUID) (AuthWorkspacePaperlessSetting, error) {
	row := q.db.QueryRow(ctx, getWorkspacePaperlessSettings, workspaceID)
	var i AuthWorkspacePaperlessSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BaseUrl,
		&i.ApiTokenEncrypted,
		&i.SyncTagsEnabled,
		&i.IsEnabled,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspacePaperlessSettings = `-- name: UpsertWorkspacePaperlessSettings :one
INSERT INTO auth.workspace_paperless_settings (id, workspace_id, base_url, api_token_encrypted, sync_tags_enabled, is_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id) DO UPDATE SET
    base_url = EXCLUDED.base_url,
    api_token_encrypted = EXCLUDED.api_token_encrypted,
    sync_tags_enabled = EXCLUDED.sync_tags_enabled,
    is_enabled = EXCLUDED.is_enabled,
    updated_at = now()
RETURNING id, workspace_id, base_url, api_token_encrypted, sync_tags_enabled, is_enabled, last_sync_at, created_at, updated_at
`

type UpsertWorkspacePaperlessSettingsParams struct {
	ID                uuid.UUID `json:"id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	BaseUrl           string    `json:"base_url"`
	ApiTokenEncrypted string    `json:"api_token_encrypted"`
	SyncTagsEnabled   *bool     `json:"sync_tags_enabled"`
	IsEnabled         *bool     `json:"is_enabled"`
}

func (q *Queries) UpsertWorkspacePaperlessSettings(ctx context.Context, arg UpsertWorkspacePaperlessSettingsParams) (AuthWorkspacePaperlessSetting, error) {
	row := q.db.QueryRow(ctx, upsertWorkspacePaperlessSettings,
		arg.ID,
		arg.WorkspaceID,
		arg.BaseUrl,
		arg.ApiTokenEncrypted,
		arg.SyncTagsEnabled,
		arg.IsEnabled,
	)
	var i AuthWorkspacePaperlessSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BaseUrl,
		&i.ApiTokenEncrypted,
		&i.SyncTagsEnabled,
		&i.IsEnabled,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
