// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countPushSubscriptionsByUser = `-- name: CountPushSubscriptionsByUser :one
SELECT COUNT(*) FROM auth.push_subscriptions WHERE user_id = $1
`

func (q *Queries) CountPushSubscriptionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPushSubscriptionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO auth.push_subscriptions (id, user_id, endpoint, p256dh, auth, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, endpoint) DO UPDATE SET
    p256dh = EXCLUDED.p256dh,
    auth = EXCLUDED.auth,
    user_agent = EXCLUDED.user_agent,
    updated_at = now()
RETURNING id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at
`

type CreatePushSubscriptionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	UserAgent *string   `json:"user_agent"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (AuthPushSubscription, error) {
	row := q.db.QueryRow(ctx, createPushSubscription,
		arg.ID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	var i AuthPushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllPushSubscriptionsByUser = `-- name: DeleteAllPushSubscriptionsByUser :exec
DELETE FROM auth.push_subscriptions WHERE user_id = $1
`

func (q *Queries) DeleteAllPushSubscriptionsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllPushSubscriptionsByUser, userID)
	return err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM auth.push_subscriptions WHERE id = $1
`

func (q *Queries) DeletePushSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, id)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM auth.push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionByEndpointParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
}

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, arg DeletePushSubscriptionByEndpointParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, arg.UserID, arg.Endpoint)
	return err
}

const getPushSubscription = `-- name: GetPushSubscription :one
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at FROM auth.push_subscriptions WHERE id = $1
`

func (q *Queries) GetPushSubscription(ctx context.Context, id uuid.UUID) (AuthPushSubscription, error) {
	row := q.db.QueryRow(ctx, getPushSubscription, id)
	var i AuthPushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPushSubscriptionByEndpoint = `-- name: GetPushSubscriptionByEndpoint :one
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at FROM auth.push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type GetPushSubscriptionByEndpointParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
}

func (q *Queries) GetPushSubscriptionByEndpoint(ctx context.Context, arg GetPushSubscriptionByEndpointParams) (AuthPushSubscription, error) {
	row := q.db.QueryRow(ctx, getPushSubscriptionByEndpoint, arg.UserID, arg.Endpoint)
	var i AuthPushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPushSubscriptions = `-- name: ListAllPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at FROM auth.push_subscriptions ORDER BY created_at DESC
`

func (q *Queries) ListAllPushSubscriptions(ctx context.Context) ([]AuthPushSubscription, error) {
	rows, err := q.db.Query(ctx, listAllPushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPushSubscription{}
	for rows.Next() {
		var i AuthPushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, updated_at FROM auth.push_subscriptions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID uuid.UUID) ([]AuthPushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPushSubscription{}
	for rows.Next() {
		var i AuthPushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
