// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: short_codes.sql

package queries

import (
	"context"
)

const shortCodeExists = `-- name: ShortCodeExists :one

SELECT EXISTS(
    SELECT 1 FROM warehouse.short_codes
    WHERE code = $1
)
`

// Shortlink registry (warehouse.short_codes, migration 005). Codes are
// globally unique; the registry is maintained by row triggers on
// items/locations/containers. Resolution for GET /r/{code} lives in
// internal/infra/postgres/shortlink_repository.go.
func (q *Queries) ShortCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, shortCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
