// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlist_items.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWishlistItemsByWorkspace = `-- name: CountWishlistItemsByWorkspace :one
SELECT COUNT(*) FROM warehouse.wishlist_items
WHERE workspace_id = $1
  AND ($2::text IS NULL OR status = $2::text)
`

type CountWishlistItemsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Status      *string   `json:"status"`
}

func (q *Queries) CountWishlistItemsByWorkspace(ctx context.Context, arg CountWishlistItemsByWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWishlistItemsByWorkspace, arg.WorkspaceID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWishlistItem = `-- name: CreateWishlistItem :one
INSERT INTO warehouse.wishlist_items (
    id, workspace_id, name, notes, url, price_estimate, currency_code,
    priority, desired_category_id, status, acquired_item_id, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, name, notes, url, price_estimate, currency_code, priority, desired_category_id, status, acquired_item_id, created_by, created_at, updated_at
`

type CreateWishlistItemParams struct {
	ID                uuid.UUID   `json:"id"`
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	Name              string      `json:"name"`
	Notes             *string     `json:"notes"`
	Url               *string     `json:"url"`
	PriceEstimate     *int32      `json:"price_estimate"`
	CurrencyCode      *string     `json:"currency_code"`
	Priority          int16       `json:"priority"`
	DesiredCategoryID pgtype.UUID `json:"desired_category_id"`
	Status            string      `json:"status"`
	AcquiredItemID    pgtype.UUID `json:"acquired_item_id"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WarehouseWishlistItem, error) {
	row := q.db.QueryRow(ctx, createWishlistItem,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Notes,
		arg.Url,
		arg.PriceEstimate,
		arg.CurrencyCode,
		arg.Priority,
		arg.DesiredCategoryID,
		arg.Status,
		arg.AcquiredItemID,
		arg.CreatedBy,
	)
	var i WarehouseWishlistItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Notes,
		&i.Url,
		&i.PriceEstimate,
		&i.CurrencyCode,
		&i.Priority,
		&i.DesiredCategoryID,
		&i.Status,
		&i.AcquiredItemID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :exec
DELETE FROM warehouse.wishlist_items
WHERE id = $1 AND workspace_id = $2
`

type DeleteWishlistItemParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error {
	_, err := q.db.Exec(ctx, deleteWishlistItem, arg.ID, arg.WorkspaceID)
	return err
}

const getWishlistItem = `-- name: GetWishlistItem :one
SELECT id, workspace_id, name, notes, url, price_estimate, currency_code, priority, desired_category_id, status, acquired_item_id, created_by, created_at, updated_at FROM warehouse.wishlist_items
WHERE id = $1 AND workspace_id = $2
`

type GetWishlistItemParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetWishlistItem(ctx context.Context, arg GetWishlistItemParams) (WarehouseWishlistItem, error) {
	row := q.db.QueryRow(ctx, getWishlistItem, arg.ID, arg.WorkspaceID)
	var i WarehouseWishlistItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Notes,
		&i.Url,
		&i.PriceEstimate,
		&i.CurrencyCode,
		&i.Priority,
		&i.DesiredCategoryID,
		&i.Status,
		&i.AcquiredItemID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWishlistItemsByWorkspace = `-- name: ListWishlistItemsByWorkspace :many
SELECT id, workspace_id, name, notes, url, price_estimate, currency_code, priority, desired_category_id, status, acquired_item_id, created_by, created_at, updated_at FROM warehouse.wishlist_items
WHERE workspace_id = $1
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY priority, created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListWishlistItemsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
	Status      *string   `json:"status"`
}

// Optional status filter; sorted by priority (1 = highest first), newest
// first within a priority. Uses the (workspace_id, status, priority) index
// when a status is given.
func (q *Queries) ListWishlistItemsByWorkspace(ctx context.Context, arg ListWishlistItemsByWorkspaceParams) ([]WarehouseWishlistItem, error) {
	rows, err := q.db.Query(ctx, listWishlistItemsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseWishlistItem{}
	for rows.Next() {
		var i WarehouseWishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Notes,
			&i.Url,
			&i.PriceEstimate,
			&i.CurrencyCode,
			&i.Priority,
			&i.DesiredCategoryID,
			&i.Status,
			&i.AcquiredItemID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWishlistItem = `-- name: UpdateWishlistItem :one
UPDATE warehouse.wishlist_items
SET name = $3,
    notes = $4,
    url = $5,
    price_estimate = $6,
    currency_code = $7,
    priority = $8,
    desired_category_id = $9,
    status = $10,
    acquired_item_id = $11,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, notes, url, price_estimate, currency_code, priority, desired_category_id, status, acquired_item_id, created_by, created_at, updated_at
`

type UpdateWishlistItemParams struct {
	ID                uuid.UUID   `json:"id"`
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	Name              string      `json:"name"`
	Notes             *string     `json:"notes"`
	Url               *string     `json:"url"`
	PriceEstimate     *int32      `json:"price_estimate"`
	CurrencyCode      *string     `json:"currency_code"`
	Priority          int16       `json:"priority"`
	DesiredCategoryID pgtype.UUID `json:"desired_category_id"`
	Status            string      `json:"status"`
	AcquiredItemID    pgtype.UUID `json:"acquired_item_id"`
}

// Full-row update used by the repository Save path. status and
// acquired_item_id are included so the acquire flow (status -> 'acquired'
// plus the link back to the created item) persists through the same query.
func (q *Queries) UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) (WarehouseWishlistItem, error) {
	row := q.db.QueryRow(ctx, updateWishlistItem,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Notes,
		arg.Url,
		arg.PriceEstimate,
		arg.CurrencyCode,
		arg.Priority,
		arg.DesiredCategoryID,
		arg.Status,
		arg.AcquiredItemID,
	)
	var i WarehouseWishlistItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Notes,
		&i.Url,
		&i.PriceEstimate,
		&i.CurrencyCode,
		&i.Priority,
		&i.DesiredCategoryID,
		&i.Status,
		&i.AcquiredItemID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
