// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO auth.workspaces (id, name, slug, description, is_personal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, description, is_personal, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	IsPersonal  bool      `json:"is_personal"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (AuthWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsPersonal,
	)
	var i AuthWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM auth.workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, description, is_personal, created_at, updated_at FROM auth.workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (AuthWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i AuthWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, description, is_personal, created_at, updated_at FROM auth.workspaces WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (AuthWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i AuthWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.name, w.slug, w.description, w.is_personal, w.created_at, w.updated_at FROM auth.workspaces w
JOIN auth.workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.name
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID uuid.UUID) ([]AuthWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthWorkspace{}
	for rows.Next() {
		var i AuthWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE auth.workspaces
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, is_personal, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (AuthWorkspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name, arg.Description)
	var i AuthWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workspaceExistsBySlug = `-- name: WorkspaceExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM auth.workspaces WHERE slug = $1)
`

func (q *Queries) WorkspaceExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
