// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_members.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkspaceOwners = `-- name: CountWorkspaceOwners :one
SELECT COUNT(*) FROM auth.workspace_members
WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO auth.workspace_members (id, workspace_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, user_id, role, invited_by, created_at, updated_at
`

type CreateMemberParams struct {
	ID          uuid.UUID             `json:"id"`
	WorkspaceID uuid.UUID             `json:"workspace_id"`
	UserID      uuid.UUID             `json:"user_id"`
	Role        AuthWorkspaceRoleEnum `json:"role"`
	InvitedBy   pgtype.UUID           `json:"invited_by"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (AuthWorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i AuthWorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM auth.workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, workspace_id, user_id, role, invited_by, created_at, updated_at FROM auth.workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (AuthWorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.UserID)
	var i AuthWorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM auth.workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetUserRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (AuthWorkspaceRoleEnum, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.WorkspaceID, arg.UserID)
	var role AuthWorkspaceRoleEnum
	err := row.Scan(&role)
	return role, err
}

const listMembersByWorkspace = `-- name: ListMembersByWorkspace :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.invited_by, wm.created_at, wm.updated_at, u.email, u.full_name
FROM auth.workspace_members wm
JOIN auth.users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at
`

type ListMembersByWorkspaceRow struct {
	ID          uuid.UUID             `json:"id"`
	WorkspaceID uuid.UUID             `json:"workspace_id"`
	UserID      uuid.UUID             `json:"user_id"`
	Role        AuthWorkspaceRoleEnum `json:"role"`
	InvitedBy   pgtype.UUID           `json:"invited_by"`
	CreatedAt   pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz    `json:"updated_at"`
	Email       string                `json:"email"`
	FullName    string                `json:"full_name"`
}

func (q *Queries) ListMembersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByWorkspaceRow{}
	for rows.Next() {
		var i ListMembersByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberExists = `-- name: MemberExists :one
SELECT EXISTS(
    SELECT 1 FROM auth.workspace_members
    WHERE workspace_id = $1 AND user_id = $2
)
`

type MemberExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) MemberExists(ctx context.Context, arg MemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberExists, arg.WorkspaceID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE auth.workspace_members
SET role = $3, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
RETURNING id, workspace_id, user_id, role, invited_by, created_at, updated_at
`

type UpdateMemberRoleParams struct {
	WorkspaceID uuid.UUID             `json:"workspace_id"`
	UserID      uuid.UUID             `json:"user_id"`
	Role        AuthWorkspaceRoleEnum `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (AuthWorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i AuthWorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
