// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const archiveCompany = `-- name: ArchiveCompany :exec
UPDATE warehouse.companies
SET is_archived = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveCompany, id)
	return err
}

const companyNameExists = `-- name: CompanyNameExists :one
SELECT EXISTS(
    SELECT 1 FROM warehouse.companies
    WHERE workspace_id = $1 AND name = $2 AND is_archived = false
)
`

type CompanyNameExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

func (q *Queries) CompanyNameExists(ctx context.Context, arg CompanyNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, companyNameExists, arg.WorkspaceID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO warehouse.companies (id, workspace_id, name, website, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, website, notes, is_archived, created_at, updated_at
`

type CreateCompanyParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Website     *string   `json:"website"`
	Notes       *string   `json:"notes"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (WarehouseCompany, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Website,
		arg.Notes,
	)
	var i WarehouseCompany
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM warehouse.companies WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, workspace_id, name, website, notes, is_archived, created_at, updated_at FROM warehouse.companies
WHERE id = $1 AND workspace_id = $2
`

type GetCompanyParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (WarehouseCompany, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.ID, arg.WorkspaceID)
	var i WarehouseCompany
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByName = `-- name: GetCompanyByName :one
SELECT id, workspace_id, name, website, notes, is_archived, created_at, updated_at FROM warehouse.companies
WHERE workspace_id = $1 AND name = $2
`

type GetCompanyByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

func (q *Queries) GetCompanyByName(ctx context.Context, arg GetCompanyByNameParams) (WarehouseCompany, error) {
	row := q.db.QueryRow(ctx, getCompanyByName, arg.WorkspaceID, arg.Name)
	var i WarehouseCompany
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, workspace_id, name, website, notes, is_archived, created_at, updated_at FROM warehouse.companies
WHERE workspace_id = $1 AND is_archived = false
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListCompaniesParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]WarehouseCompany, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseCompany{}
	for rows.Next() {
		var i WarehouseCompany
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Website,
			&i.Notes,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCompany = `-- name: RestoreCompany :exec
UPDATE warehouse.companies
SET is_archived = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreCompany, id)
	return err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE warehouse.companies
SET name = $2, website = $3, notes = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, website, notes, is_archived, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Website *string   `json:"website"`
	Notes   *string   `json:"notes"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (WarehouseCompany, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Website,
		arg.Notes,
	)
	var i WarehouseCompany
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
