// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const archiveLabel = `-- name: ArchiveLabel :exec
UPDATE warehouse.labels
SET is_archived = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveLabel, id)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO warehouse.labels (id, workspace_id, name, color, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, color, description, is_archived, created_at, updated_at
`

type CreateLabelParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Color       *string   `json:"color"`
	Description *string   `json:"description"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (WarehouseLabel, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
		arg.Description,
	)
	var i WarehouseLabel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM warehouse.labels WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, name, color, description, is_archived, created_at, updated_at FROM warehouse.labels
WHERE id = $1 AND workspace_id = $2
`

type GetLabelParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetLabel(ctx context.Context, arg GetLabelParams) (WarehouseLabel, error) {
	row := q.db.QueryRow(ctx, getLabel, arg.ID, arg.WorkspaceID)
	var i WarehouseLabel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabelByName = `-- name: GetLabelByName :one
SELECT id, workspace_id, name, color, description, is_archived, created_at, updated_at FROM warehouse.labels
WHERE workspace_id = $1 AND name = $2
`

type GetLabelByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

func (q *Queries) GetLabelByName(ctx context.Context, arg GetLabelByNameParams) (WarehouseLabel, error) {
	row := q.db.QueryRow(ctx, getLabelByName, arg.WorkspaceID, arg.Name)
	var i WarehouseLabel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const labelNameExists = `-- name: LabelNameExists :one
SELECT EXISTS(
    SELECT 1 FROM warehouse.labels
    WHERE workspace_id = $1 AND name = $2 AND is_archived = false
)
`

type LabelNameExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

func (q *Queries) LabelNameExists(ctx context.Context, arg LabelNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, labelNameExists, arg.WorkspaceID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, workspace_id, name, color, description, is_archived, created_at, updated_at FROM warehouse.labels
WHERE workspace_id = $1 AND is_archived = false
ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, workspaceID uuid.UUID) ([]WarehouseLabel, error) {
	rows, err := q.db.Query(ctx, listLabels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WarehouseLabel{}
	for rows.Next() {
		var i WarehouseLabel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLabel = `-- name: RestoreLabel :exec
UPDATE warehouse.labels
SET is_archived = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreLabel, id)
	return err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE warehouse.labels
SET name = $2, color = $3, description = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, color, description, is_archived, created_at, updated_at
`

type UpdateLabelParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Color       *string   `json:"color"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (WarehouseLabel, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Description,
	)
	var i WarehouseLabel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
